module Javascript
  ArrayLiteral        = Struct.new(:elements)
  Assignment          = Struct.new(:operator, :left_hand_side, :right_hand_side)
  BinaryOperation     = Struct.new(:operator, :left_hand_side, :right_hand_side)
  Block               = Struct.new(:body)
  BooleanLiteral      = Struct.new(:value, keyword_init: true)
  ExpressionStatement = Struct.new(:expression)
  FunctionCall        = Struct.new(:callee, :arguments)
  FunctionDeclaration = Struct.new(:definition)
  FunctionDefinition  = Struct.new(:name, :parameters, :body, :variables)
  Identifier          = Struct.new(:name)
  If                  = Struct.new(:condition, :consequent, :alternative)
  NumberLiteral       = Struct.new(:value)
  NullLiteral         = Struct.new(nil)
  ObjectLiteral       = Struct.new(:properties)
  Parameter           = Struct.new(:name, :default)
  PropertyAccess      = Struct.new(:receiver, :accessor, :computed)
  PropertyDefinition  = Struct.new(:name, :value, keyword_init: true)
  Return              = Struct.new(:expression)
  Script              = Struct.new(:statement_list, :variables)
  StatementList       = Struct.new(:statements)
  StringLiteral       = Struct.new(:value)
  Ternary             = Struct.new(:condition, :consequent, :alternative)
  UnaryOperation      = Struct.new(:operator, :operand, :position)
  VariableDeclaration = Struct.new(:name, :value)
  VariableStatement   = Struct.new(:declarations, keyword_init: true)
end
